sudo: required
language: generic
services:
  - docker


before_install:
  - docker build -t johnsonsusai/docker-react -f Dockerfile.dev .

script:
  #- docker run johnsonsusai/docker-react npm run test -- --coverage
   - docker run -e CI=true johnsonsusai/docker-react npm run test